scss_files: '_sass/**/*.scss'

exclude: 'css/main.scss'

linters:

  PropertySortOrder:
    order: concentric

  SelectorFormat:
    convention: hyphenated_BEM

  PropertySpelling:
    extra_properties:
      - cx
      - cy

  PropertyUnits:
    global: ['rem', '%', 's', 'vw', 'vh']
    properties:
      border: ['px', 'rem']
